### ISSUE TITLE
Last Projects

### ISSUE THREAD

**Issue by Kay-Kleinvogel** [Ironlors/open-bpmn#5]
There should be a list of my latest open projects on the landing page. From there I can easily load them into the editor.

**TODO:**
- [x] create a queue data structure for the last projects
- [x] implement the queueing when opening or saving a project
- [x] add an interface to show the current content of the queue
- [x] allow the possibility to open a project directly from the interface

**Comment by Kay-Kleinvogel** [comment]
Feature added in 91e011e
